package com.siuts.siutsapplication.domain;

public enum Birds {
    PARUS_MAJOR,
    FRINGILLA_COELEBS,
    TURDUS_MERULA,
    EMBERIZA_CITRINELLA,
    CHLORIS_CHLORIS,
    APUS_APUS,
    PHOENICURUS_PHOENICURUS,
    LOCUSTELLA_FLUVIATILIS,
    PHYLLOSCOPUS_SIBILATRIX,
    DENDROCOPOS_MAJOR,
}
